# Generated by Django 4.2.1 on 2023-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_income_delete_incomesource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbudget',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
