# Generated by Django 4.2.1 on 2023-07-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_expenseitem_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.personalbudget'),
        ),
    ]
