# Generated by Django 4.2.1 on 2023-07-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_income_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalbudget',
            name='budget_amount',
        ),
    ]
