# Generated by Django 4.2.1 on 2023-07-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_personalbudget_budget_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalbudget',
            name='related_expenses',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main_app.personalbudget'),
        ),
    ]
